facts : {
    blocklist : [ 
        "cloud",
        "dhcp_servers",
        "EC2",
        "file system",
        "GCE",
        "hypervisors",
        "is_virtual",
        "virtualization"
        "Xen"
    ]
}
