# /etc/sysctl.conf
# Managed by puppet!
# For more information on how this file works, please see
# the manpages sysctl(8) and sysctl.conf(5).

net.ipv4.ip_forward = 0
fs.inotify.max_user_watches=524288
